### PR TITLE
needs initial values even though optional

### PR DESCRIPTION
**Pull request by tnmt**
hi, @hfm 

I met below error, and I don't set these parameters.

```
Error: Evaluation Error: Error while evaluating a Function Call, Class[Stns::Client]:
  expects a value for parameter 'auth_token'
  expects a value for parameter 'wrapper_path'
  expects a value for parameter 'chain_ssh_wrapper'
  expects a value for parameter 'request_timeout'
  expects a value for parameter 'request_retry'
  expects a value for parameter 'uid_shift'
  expects a value for parameter 'gid_shift'
```

this is example that using `stns::client` and `stns::server` seems same.

Do you think this patch is correct?

### CODE REVIEW

**Comment by hfm** [comment]
Yes, it's correct for Puppet 4.
I'll fix CI failures before merge this PR.

**Comment by hfm** [comment]
@tnmt Sorry late response. I fixed CI on #41 . Please update this branch.

**Comment by tnmt** [comment]
Thank you.

I rebased my commit. Please review again.

**Review by hfm — APPROVED** [review]

**Comment by hfm** [comment]
Thanks for your patch! I released https://forge.puppet.com/hfm/stns/3.0.1

**Pull request merged**
